apiVersion: apps/v1
kind: Deployment
metadata:
   name: app-deployment
   labels:
      app: myapp
spec: 
  replicas: 1
  selector:
    matchLabels:
       app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ang-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
     # imagePullSecrets:
      #  -  name: nexus-secret    

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
     app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80     
