apiVersion: apps/v1
kind: Deployment
metadata:
   name: app-deployment
   labels:
      app: myapp
spec: 
  replicas: 1
  selector:
    matchLabels:
       app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 127.0.0.1:9001/repository/docker_nexus/ang-app:01
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
     app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80     